<?php

/********************
 *
 * Author:      Des Jones
 * Project:     xi
 * Date:        Mon 25 Oct 19:10:13 BST 2021
 * Version:     1.0
 *
 *****************************************/

class define {

    const DEBUG = true;
    const VERSION = "9";
    const DOCUMENT_ROOT = "/var/www/xi/xi.localdomain/htdocs/";
    const SHARED_VIEWS = "/var/www/xi/xi.localdomain/htdocs/include/";
    const TEMPLATE_DIR_RELATIVE_TO_CLASS = "/../template/";
    const TEMPLATE_DEFAULT = "smartadmin.inc";
    const TEMPLATE_BOOTSTRAP = "bootstrap.inc";
    const PAGE_SUFFIX = ".html";
    const USER_SESSION_KEY = "usersession";
    const UNIQUEID_SESSION_KEY = "unqiueidsession";
    const REQUESTID_SESSION_KEY = "requestid";
    const REQUESTID_REQUEST_KEY = "requestid";
    const SYSTEM_SUPERUSERID = "1";
    const SYSTEM_USERID = "2";
    const SYSTEM_GUESTID = "3";
    const SYSTEM_SUPERUSER_NICKNAME = "superuser";
    const SYSTEM_USER_NICKNAME = "system";
    const SYSTEM_GUEST_NICKNAME = "guest";
    const ANONYMOUS_THUMB_MD5SUM = "b732c574cdf48bc71795d75cb0e2b5fe";
    const ANONYMOUS_THUMB_BYTES = "24403";

}
