<div class="input-group input-group-lg hidden-mobile">
        <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Active <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                        <li class="active">
                                <a href="javascript:void(0)"><i class="fa fa-check"></i> Everything</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <a href="javascript:void(0)">All</a>
                        </li>
                        <li>
                                <a href="javascript:void(0)">On Leave</a>
                        </li>
                        <li>
                                <a href="javascript:void(0)">Inactive</a>
                        </li>
                </ul>
        </div>
        <input class="form-control input-lg" type="text" placeholder="Search again..." id="search-project">
        <div class="input-group-btn">
                <button type="submit" class="btn btn-default">
                        &nbsp;&nbsp;&nbsp;<i class="fa fa-fw fa-search fa-lg"></i>&nbsp;&nbsp;&nbsp;
                </button>
        </div>
</div>
<?php
