<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
    </button>
    <h4 class="modal-title" id="myModalLabel">Article Post TEST</h4>
</div>
<div class="modal-body">
    <div class="row">
            <div class="col-md-12">
                    <div class="form-group">
                            <input type="text" class="form-control" placeholder="Title" required />
                    </div>
                    <div class="form-group">
                            <textarea class="form-control" placeholder="Content" rows="5" required></textarea>
                    </div>
            </div>
    </div>
    <div class="row">
            <div class="col-md-6">
                    <div class="form-group">
                            <label for="category"> Category</label>
                            <select class="form-control" id="category">
                                    <option>Articles</option>
                                    <option>Tutorials</option>
                                    <option>Freebies</option>
                            </select>
                    </div>
            </div>
            <div class="col-md-6">
                    <div class="form-group">
                            <label for="tags"> Tags</label>
                            <input type="text" class="form-control" id="tags" placeholder="Tags" />
                    </div>
            </div>
    </div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">
            Cancel
    </button>
    <button type="button" class="btn btn-primary">
            Post Article
    </button>
</div>


