<!-- Modal -->
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="modal1Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<a class="btn btn-primary btn-lg" data-toggle="modal" href="/ajax.html?action=controller_smartadmin.modal" data-target="#modal1">Launch Ajax Modal</a>